package net.mrsistemas.healthy.data.healthyDataService;


import net.mrsistemas.healthy.data.business.model.DataUser;
import net.mrsistemas.healthy.data.business.model.User;
import net.mrsistemas.healthy.data.business.repository.UserRepository;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.assertj.core.api.Assertions.assertThat;


@RunWith(SpringRunner.class)
@SpringBootTest
public class MongoDbAutoGeneratedFieldIntegrationTest {

    @Autowired
    UserRepository userRepository;

    @Test
    public void contextLoads() {}

    @Test
    public void givenUserObject_whenSave_thenCreateNewUser() {

        User user = new User();
        user.setId(2019000024L);
        user.setData(DataUser.builder()
                .dni("8870375")
                .id(20190902000046L)
                .nombres("Max Fredis")
                .apellidos(" Tovar Hernandez")
                .ciudad("Bogota")
                .direccion("Cl 6 A 89 -  42 Interior 5 Apto 501")
                .movil("3014687812")
                .email("maxther911@gmail.com")
                .pais("Colombia")
                .build());
        userRepository.save(user);
        assertThat(userRepository.findAll().size()).isGreaterThan(0);
    }


}
